### ISSUE TITLE
Configurable burst size

### ISSUE THREAD

**Issue by SoerenBusse** [rtbrick/bngblaster#283]
**Is your feature request related to a problem? Please describe.**
When running one wing of BNG Blaster via a 10GbE interface and the other one via a 1GbE interface, we see some massive bursts at the beginning of the tests. This burst will make the buffer of the 1GbE device overflow and result in paket-drop, although the PPS-rate is still within the 1GbE limit.

![image](https://github.com/user-attachments/assets/d53c2826-8a16-4186-a934-a147c5483941)

**Describe the solution you'd like**

Currently, BNG Blaster uses 100ms bursts. We'd like to have the possibility to configure the burst-size in microseconds. https://github.com/rtbrick/bngblaster/blob/1aa3bf4d1fe6872e5ec3050f4f646580208c4229/code/bngblaster/src/bbl_stream.c#L1505C1-L1505C5

**Comment by GIC-de** [comment]
There is a new configuration option `traffic->stream-burst-ms` (cc6699d) which allows to change the default stream burst size of 100ms in a range between 1 and 1000ms. 

I also fixed the initial micro bursts  (0522f17) so your issue might be also fixed even if you remain the `stream-burst-ms` on default value of 100ms.

**Comment by SoerenBusse** [comment]
Hi @GIC-de,

thank you very much for the quick fix! `stream-burst-ms` works as expected!

While the initial burst looks a little bit better, I still see a huge burst within the first (2.135s - 2.085s) = 0,05s = 50ms, when having the default burst size auf 100ms. Within this time-frame, it's sending 11500 packets with a frame-size of 1052 bytes, which is equivalent to around 12MB  (~ 2Gbit/s).

![image](https://github.com/user-attachments/assets/d491e5b1-1aa9-4a31-8698-b3940d9bc108)

**Comment by GIC-de** [comment]
Could you share the actual configuration and start parameters for me to better understand the issue. You can also send to <bngblaster@rtbrick.com>.

**Comment by GIC-de** [comment]
What happens after two seconds? Why is traffic starting after two seconds?

**Comment by GIC-de** [comment]
I may find the reason (2f0e2e0), can you try again please?

**Comment by SoerenBusse** [comment]
Hi @GIC-de,

@slieberth did further in depth analysis and we're definitely still seeing a burst at the beginning. See attached screenshot. Red ist BNGBlaster sending (Downstream) and blue what received on an access port behind the BNG.

<img width="887" alt="tmp_5fb83341-215f-4f61-9d3f-d34ef16967e2" src="https://github.com/user-attachments/assets/6eecab51-aa88-4e91-9b9d-fb801d248b57">

**Comment by GIC-de** [comment]
Could you filter on BNG Blaster stream traffic and show complete display filter in screenshot please! If not filtered on traffic streams, the peak in the beginning is control traffic. Ideally, could you attach PCAP or send via Mail to bngblaster@rtbrick.com.

**Comment by SoerenBusse** [comment]
After some debugging, it looks like I may have found the root cause. I'm using A10-NSP with PPPoE access, a `tx-interval of 0.1`, no threading and a voice downstream queue of `14000pps`, which results in `io_bucket->nsec = 71428ns ~= 0.071ms`. 

If `nsec < tx-interval`, as in this example, `io_bucket->base` is incremented by `71428ns` for every 0.1ms interval. In this case, the difference between `now` and `io_bucket->base`, which is used here, will increase with each interval. As I understand it, this behavior is intended and used to send the correct pps rate: 
https://github.com/rtbrick/bngblaster/blob/main/code/bngblaster/src/bbl_stream.c#L1548
![image](https://github.com/user-attachments/assets/daecfd96-0cc7-41c5-8edf-c2265ae43552)

However, the stream frames are only sent when the session is in `PROTOCOL_SUCCESS`: https://github.com/rtbrick/bngblaster/blob/main/code/bngblaster/src/bbl_stream.c#L1554
Between "protocol initialization begin" and "protocol setup successful", the "pps-rate algorithm" described above is running, and increasing the difference (in code it's variable expired) indefinitely. When the protocol setup is complete, base is reset to `min = now - burst-size` if necessary and a burst of frames is sent until `expired < stream->expired`.

The attached log file shows this behavior quite well.
[bngblaster-burst.log](https://github.com/user-attachments/files/17850930/bngblaster-burst.log)
`Invalid protocol state` logging is here: https://github.com/rtbrick/bngblaster/tree/main/code/bngblaster/src#L1559
`Burst Counter` logging is here: https://github.com/rtbrick/bngblaster/blob/main/code/bngblaster/src/io/io_raw.c#L153

In summary, the initial burst depends on how long the protocol negotiation takes. When testing PPPoverL2TP, we're seeing a larger burst than when using PPPoE over A10-NSP. I suppose the reason we're seeing these bursts in our environment is because all our tests are running over a GPON network, which introduces more latency than plain Ethernet. I don't see any bursts when using veth.

I think this behavior is a bug and the "pps-rate algorithm" should only start after the protocol has been successfully established.
For testing purposes, I added `io_bucket->base = now` to keep the `base` the same as `now` while the protocol is being negotiated, preventing `expired` to increasing indefinitely.
```c
        while (stream) {
            // LOG(IO, "State: Now is %lu, Base is %lu, Expired is %lu\n", now, io_bucket->base, expired);
            if (stream->expired > expired) {
                io_bucket->stream_cur = stream;
                break;
            }
            if (bbl_stream_io_send(stream) == PROTOCOL_SUCCESS) {
                io_bucket->stream_cur = stream->io_next;
                io->bucket_cur = io_bucket;
                return stream;
            }

            LOG(IO, "Invalid protocol state: Now is %lu, Base is %lu, Expired is %lu\n", now, io_bucket->base, expired);
            stream = stream->io_next;
            // ADDED
            io_bucket->base = now;
        }
```
With this workaround, I don't see any bursts at the beginning.
![image](https://github.com/user-attachments/assets/f356a74b-983e-4c65-8048-a01436f7751e)

For me, it's hard to find the correct way how to fix this bug, without breaking other test-cases or introducing new side effects. @GIC-de maybe you can take a look into it.

**Comment by GIC-de** [comment]
Can you try following commit (branch: `stream_bursts`):

```
commit 324bb3fdd7c3563bb9974f4e003c080b84d49daa (HEAD -> stream_bursts, origin/stream_bursts)
Author: Christian Giese <christian@rtbrick.com>
Date:   Tue Nov 26 13:23:24 2024 +0000

    reduce initial burst (#283)

diff --git a/code/bngblaster/src/bbl_stream.c b/code/bngblaster/src/bbl_stream.c
index 73bf9ac..dbb51ab 100644
--- a/code/bngblaster/src/bbl_stream.c
+++ b/code/bngblaster/src/bbl_stream.c
@@ -1558,7 +1558,14 @@ bbl_stream_io_send_iter(io_handle_s *io, uint64_t now)
             }
             stream = stream->io_next;
         }
-        if(!stream) io_bucket->stream_cur = NULL;
+        if(!stream) {
+            if(io_bucket->stream_cur == io_bucket->stream_head) {
+                /* We can reset bucket base if none of the streams
+                 * in the bucket is active. */
+                io_bucket->base = 0;
+            }
+            io_bucket->stream_cur = NULL;
+        }
         /* next bucket */
         io_bucket = io_bucket->next;
         if(!io_bucket) io_bucket = io->bucket_head; 
```

**Comment by SoerenBusse** [comment]
@GIC-de 
Can confirm, that this fixes the bug! Thank you very much!
![image](https://github.com/user-attachments/assets/579bec5b-f00a-4706-b615-dc2ef99c3fd5)
